### PR TITLE
Fix expiration fork usage

### LINKED ISSUE #287: expiration fork isn't set in miner.cpp
The fork expiration isn't set in miner.cpp. This causes a failure when testing mining on regtest (when mining past the expiration fork -- use the fuzz test). This is because the mined block doesn't have the same expiration time that the block validation uses.

I'd like to see us remove the expiration time state from claimtrie and claimtriecache. It should check the expiration height computation in overloaded methods like we do for normalization. This won't be any worse performance because we do the check in validation.cpp on every increment/decrement anyhow.

### PR DESCRIPTION
**Pull request by bvbfan**
Signed-off-by: Anthony Fieroni <bvbfan@abv.bg>

Fixes #287

### CODE REVIEW

File: src/test/claimtriebranching_tests.cpp [hunk 1]
```diff
@@ -1723,7 +1723,7 @@ BOOST_AUTO_TEST_CASE(normalization_does_not_kill_sort_order)
 BOOST_AUTO_TEST_CASE(normalization_does_not_kill_expirations)
 {
     ClaimTrieChainFixture fixture;
-    fixture.setExpirationTime(3);
+    fixture.setExpirationForkHeight(800, 3, 800);
```
Comment (BrannonKing) [inline src/test/claimtriebranching_tests.cpp]: I don't think this is right. Aren't those 800s supposed to be 140, the current height?

Comment (bvbfan) [reply src/test/claimtriebranching_tests.cpp]: In ClaimTrieChainFixture we don't change the consensus, so setExpirationTime was supposed to changed only expiration time, since we don't have such functionality it should be
```
fixture.setExpirationForkHeight(consensus.nExtendedClaimExpirationForkHeight, 3, consensus.nExtendedClaimExpirationTime)
```
